using JualBeli_LIB;
using MySql.Data.MySqlClient;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Jabatan
{
    public Jabatan()
    {
        IdJabatan = "";
    }

    public Jabatan(string idJabatan, string namaJabatan)
    {
        IdJabatan = idJabatan;
        NamaJabatan = namaJabatan;
    }

	public virtual string IdJabatan
	{
		get;
		set;
	}

	public virtual string NamaJabatan
	{
		get;
		set;
    }

    #region Methode
    public static string GenerateKode(out string hasilKode)
    {
        string sql = "select max(substring(IdJabatan, 2)) from jabatan;";
        hasilKode = "";

        try
        {
            MySqlDataReader hasil = Koneksi.jalankanPerintahQuery(sql);

            if (hasil.Read() == true)
            {
                int kodeTerbaru = int.Parse(hasil.GetValue(0).ToString()) + 1;

                hasilKode = "J" + kodeTerbaru;
            }
            else
            {
                hasilKode = "J1";
            }

            return "1";
        }
        catch (Exception e)
        {
            return e.Message;
        }
    }

    public static string BacaData(string kriteria, string nilaiKriteria, List<Jabatan> listDatakategori)
    {
        string sql = "";

        if (kriteria == "")
        {
            sql = "select * from jabatan;";
        }
        else
        {
            sql = "select * from jabatan where " + kriteria + " like '%" + nilaiKriteria + "%';";
        }

        try
        {
            MySqlDataReader hasil = Koneksi.jalankanPerintahQuery(sql);

            while (hasil.Read() == true)
            {
                Jabatan jbt = new Jabatan();
                jbt.IdJabatan = hasil.GetValue(0).ToString();
                jbt.NamaJabatan = hasil.GetValue(1).ToString();

                listDatakategori.Add(jbt);
            }

            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message;
        }
    }

    public static string TambahJabatan(Jabatan jbt)
    {
        string sql = "insert into jabatan values ('" + jbt.IdJabatan + "','" + jbt.NamaJabatan + "');";

        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + ". perintah sql : " + sql;
        }
    }

    public static string UbahJabatan(Jabatan jbt)
    {
        string sql = "update jabatan set Nama='" + jbt.NamaJabatan+"' where IdJabatan = '"+ jbt.IdJabatan+"';";

        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + ". perintah sql : " + sql;
        }
    }

    public static string HapusJabatan(Jabatan jbt)
    {
        string sql = "delete from jabatan where IdJabatan = '" + jbt.IdJabatan + "';";

        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + ". perintah sql : " + sql;
        }
    }
    #endregion
}

