using JualBeli_LIB;
using MySql.Data.MySqlClient;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Supplier
{
	public virtual int KodeSupplier
	{
		get;
		set;
	}

	public virtual string Nama
	{
		get;
		set;
	}

	public virtual string Alamat
	{
		get;
		set;
	}

    public virtual string Telpon
    {
        get;
        set;
    }
    public Supplier()
    {
        KodeSupplier = 0;
        Nama = "";
        Alamat = "";
        Telpon = "";
    }
    public Supplier(int pKode, string pNama, string pAlamat, string pTelpon)
    {
        KodeSupplier = pKode;
        Nama = pNama;
        Alamat = pAlamat;
        Telpon = pTelpon;
    }

    public static string TambahData(Supplier supplier)
    {
        string sql = "insert into supplier values ('" + supplier.KodeSupplier + "','" + supplier.Nama + "','" + supplier.Alamat + "','" + supplier.Telpon + "');";
        
        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + " perintah sql: " + sql;
        }
    }

    public static string UbahData(Supplier supplier)
    {
        string sql = "update supplier set Nama = '" + supplier.Nama + "', Alamat = '" + supplier.Alamat + "', Telpon = '" + supplier.Telpon + "' where KodeSupplier = '" + supplier.KodeSupplier + "';";
        
        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + " perintah sql: " + sql;
        }
    }

    public static string HapusData(Supplier supplier)
    {
        string sql = "delete from supplier where KodeSupplier =  '" + supplier.KodeSupplier + "';";

        try
        {
            Koneksi.DML(sql);
            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + " perintah sql: " + sql;
        }
    }

    public static string BacaData(string kriteria, string nilaiKriteria, List<Supplier> listHasilData)
    {
        string sql = "";
        if (kriteria == "")
        {
            sql = "select * from supplier";
        }
        else
        {
            sql = "select * from supplier where " + kriteria + " like '%" + nilaiKriteria + "%';";
        }

        try
        {
            MySqlDataReader hasilData = Koneksi.jalankanPerintahQuery(sql);

            while (hasilData.Read() == true)
            {
                Supplier kt = new Supplier();
                kt.KodeSupplier = int.Parse(hasilData.GetValue(0).ToString());
                kt.Nama = hasilData.GetValue(1).ToString();
                kt.Alamat = hasilData.GetValue(2).ToString();
                kt.Telpon = hasilData.GetValue(3).ToString();

                listHasilData.Add(kt);
            }

            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message + ". Perintah Sql: " + sql;
        }
    }

    public static string GenerateKode(out string hasilKode)
    {
        string sql = "select max(KodeSupplier) from supplier;";

        hasilKode = "";

        try
        {
            MySqlDataReader hasiLData = Koneksi.jalankanPerintahQuery(sql);

            if (hasiLData.Read() == true)
            {
                int kodeTerbaru = int.Parse(hasiLData.GetValue(0).ToString()) + 1;

                if (kodeTerbaru < 10)
                {
                    hasilKode = "0" + kodeTerbaru.ToString();
                }
                else
                {
                    hasilKode = kodeTerbaru.ToString();
                }
            }
            else
            {
                hasilKode = "01";
            }

            return "1";
        }
        catch (MySqlException ex)
        {
            return ex.Message;
        }
    }
}

